language: csharp
mono:
  - 5.0.1
solution: B9PartSwitch.sln
install:
  - bundle install
  - build_script/install/install_ksp_dlls.sh
  - nuget restore ${TRAVIS_SOLUTION}
script:
  - msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" ${TRAVIS_SOLUTION}
  - bin/test
  - build_script/script/make_release.sh
  - build_script/script/avc_version.rb files/B9PartSwitch.version.erb release/GameData/B9PartSwitch/B9PartSwitch.version
  - build_script/script/make_zip.sh
after_success:
  - build_script/before_deploy/copy_zip.sh
  - mkdir bintray
  - build_script/before_deploy/populate_bintray.rb files/bintray/publish_build.json.erb bintray/publish_build.json
  - build_script/before_deploy/populate_bintray.rb files/bintray/publish_avc_version.json.erb bintray/publish_avc_version.json
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_SECRET_ACCESS_KEY}
    bucket: blowfish-ksp-b9partswitch-dev-builds
    local_dir: zip_release/s3/
    upload-dir: ${TRAVIS_BRANCH}
    on:
      all_branches: true
  - provider: bintray
    file: bintray/publish_build.json
    user: blowfishpro
    key: ${BINTRAY_API_KEY}
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_DEPLOY_TOKEN}
    file: zip_release/github/*.zip
    file_glob: true
    name: "${PROJECT_NAME} ${TRAVIS_TAG} for KSP ${KSP_VERSION}"
    on:
      tags: true
  - provider: bintray
    file: bintray/publish_avc_version.json
    user: blowfishpro
    key: ${BINTRAY_API_KEY}
    on:
      tags: true
env:
  global:
    - PROJECT_NAME="B9PartSwitch"
    - PROJECT_DIR="B9PartSwitch"
    - KSP_VERSION="$(cat KSP_VERSION)"
    - KSP_DLL_PATH="${TRAVIS_BUILD_DIR}/KSP_DLLs/${KSP_VERSION}"
notifications:
  email: false
git:
  depth: 200
