language: csharp
solution: B9PartSwitch.sln
install:
  - build_script/install/install_ksp_dlls.sh
  - nuget restore ${TRAVIS_SOLUTION}
script:
  - msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" ${TRAVIS_SOLUTION}
  - bin/test
  - build_script/script/avc_version.rb
  - build_script/script/make_zip.sh
before_deploy:
  - build_script/before_deploy/copy_zip.sh
deploy:
  - provider: bintray
    file: build_script/deploy/bintray_deploy.json
    user: blowfishpro
    key: ${BINTRAY_API_KEY}
  - provider: releases
    api_key: ${GITHUB_DEPLOY_TOKEN}
    file: zip_release/github/*.zip
    file_glob: true
    name: "${PROJECT_NAME} ${TRAVIS_TAG} for KSP ${KSP_VERSION}"
    on:
      tags: true
  - provider: bintray
    file: build_script/deploy/bintray_release_version.json
    user: blowfishpro
    key: ${BINTRAY_API_KEY}
    on:
      tags: true
env:
  global:
    - PROJECT_NAME="B9PartSwitch"
    - PROJECT_DIR="B9PartSwitch"
    - KSP_VERSION="$(cat KSP_VERSION)"
    - KSP_DLL_PATH="${TRAVIS_BUILD_DIR}/KSP_DLLs/${KSP_VERSION}"
notifications:
  email: false
git:
  depth: 200
